# server의 port 설정
server:
  port: 80

# 연결할 데이터베이스 설정 - MySQL
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kabigon?useUnicode=yes&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: kabigon
    password: jjansu88

# 연결할 데이터베이스 설정 - Oracle
# spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver
# spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
# spring.datasource.username=kabigon
# spring.datasource.password=jjansu88

  jpa:
    show-sql: true
    
    hibernate:
      ddl-auto: update
      
    properties:
      hibernate:
        format_sql: true

  devtools:
    livereload:
      enabled: true
  
  thymeleaf:
    cache: false

# 파일 업로드 설정    
  servlet:
    multipart:
      enabled: true            
      location: E:\\BlockChain\\Spring_Boot(STS)\\TempRepository
      max-request-size: 30MB
      max-file-size: 10MB

com:
  kabigon:
    upload:
      path: E:\\BlockChain\\Spring_Boot(STS)\\TempRepository

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
            
