# 환경의 변화가 생겼을 때 수정할 정적 상수를 속성으로 생성
com:
  paori:
    profile:
      upload:
        path: C:\\Users\\notep\\Documents\\DataRepository

# server의 port 설정
server:
  port: 80

# 연결할 데이터베이스 설정 - MySQL
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/project?useUnicode=yes&characterEncoding=UTF-8&serverTimezone=UTC
    username: kabigon
    password: jjansu88

# 연결할 데이터베이스 설정 - Oracle
# spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver
# spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
# spring.datasource.username=kabigon
# spring.datasource.password=jjansu88

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        
  devtools:
    livereload:
      enabled: true
    remote:
      restart:
        enabled: true

  thymeleaf:
    cache: false

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace